### ISSUE TITLE
Font size is too small when viewed in Chrome

### ISSUE THREAD

**Issue by mattdiamond** [leanprover-community/lean-web-editor#1]
Here's how the web editor appears in Chrome (Mac OSX 10.12):

![image](https://user-images.githubusercontent.com/674060/91647874-42e63600-ea2e-11ea-8a76-c0f88b442a83.png)

In contrast, here's how it appears in Firefox:

![image](https://user-images.githubusercontent.com/674060/91647892-8c368580-ea2e-11ea-97f4-60b297512abc.png)

The difference can be traced back to the changes introduced in commit 87c9ddb, specifically the way `fontSize` is set. In Firefox `minimumFontSize` ends up being 1 and `fontSize` is set to `null`, which I assume results in Monaco falling back to some default value; in Chrome `minimumFontSize` is 6 and `fontSize` is therefore set to 6 (though the font size ends up being 8px for some reason).

Not sure what the solution is here... normally I would say "just don't set the font size", but clearly the above commit was made in response to a bug that arose because the font-size wasn't being set. Perhaps there's a better way of working around the original bug, e.g. setting `fontSize` to `Math.max(DEFAULT_FONT_SIZE, minimumFontSize)` with `DEFAULT_FONT_SIZE` set to something reasonable like `12`.

(On a side note, regarding the "minimum font size" issue that necessitated the fix in 87c9ddb: is the original Lean Web Editor also susceptible to that issue, and if so, should it be patched as well? Or is that issue specific to this fork?)

**Comment by bryangingechen** [comment]
Thanks for the report! Indeed, I made this change in response to a report from that the lines were overlapping in Firefox when zooming in a few levels (see [this Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/187764-Lean-for.20teaching/topic/Next.20step.20after.20the.20Logic.20and.20Proofs/near/176271518)).

However, I can't reproduce what you're seeing in Firefox 80 and Chrome 85 on macOS 10.14.6. Here's a screenshot of Firefox:
<img width="1680" alt="Screen Shot 2020-08-29 at 9 16 40 PM" src="https://user-images.githubusercontent.com/5209952/91649017-f2c2a000-ea3c-11ea-824d-c59d92bd60fc.png">


Here's a screenshot of Chrome:
<img width="1680" alt="Screen Shot 2020-08-29 at 9 13 42 PM" src="https://user-images.githubusercontent.com/5209952/91648987-89db2800-ea3c-11ea-9764-ce576cd27e5b.png">

Are you using some special settings (or am I)?

To be honest, I think I copied this workaround from some StackOverflow post, so I'm definitely open to better solutions. I tested the `Math.max(DEFAULT_FONT_SIZE, minimumFontSize)` idea and it doesn't break things for me, so if you can confirm that that fixes things for you I'd be happy to commit that.

Regarding the original Lean Web Editor, it's essentially unmaintained at this point, as the Lean developers are focused on Lean 4. So I don't think it's likely to be patched.

**Comment by mattdiamond** [comment]
That's strange that you can't reproduce it... perhaps it has something to do with the difference in MacOS version or a Chrome setting (maybe hardware acceleration?). Regardless, the solution using `Math.max` does appear to fix things on my end, so that works for me. Thanks for responding!

**Comment by bryangingechen** [comment]
OK, feel free to ping me again if things are still wonky after tonight's deploy (probably in 5-6 hours).

**Comment by mattdiamond** [comment]
Sounds good, thanks for taking care of this!
