### ISSUE TITLE
Cursor moves to the wrong place after typing unicode shorthands

### ISSUE THREAD

**Issue by eric-wieser** [leanprover-community/lean-web-editor#2]
If I have `12345|67890ABC` where `|` is the cursor, and type `\forall ` (with a space), then the result is `12345∀ 67890A|BC` - the cursor is not correctly adjusted for the 6 character shrinkage between `\forall` and `∀`

**Comment by bryangingechen** [comment]
Thanks for the report! This should be fixed in https://github.com/leanprover-community/lean-web-editor/commit/c2bbeb3863ca7cab2b6ad7d22046ec35bc9e44e6.
