### ISSUE TITLE
"Lean is busy..." persists indefinitely

### ISSUE THREAD

**Issue by TheDocTrier** [leanprover-community/lean-web-editor#6]
When opening https://leanprover-community.github.io/lean-web-editor/ on Firefox 113.0 (64-bit) on Ubuntu, the header reads "Lean is busy..." and continues to do so indefinitely. Looking at the JS console shows this error before loading appears to stop:

```
TypeError: Module.FS.createFolder is not a function 56 06a8de4b9c87b51e92ec.worker.js:8:49738
```

Clearing both the library cache & JS/WASM cache did not resolve the issue.

**Comment by eric-wieser** [comment]
See https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Web.20editor.20not.20working/near/360726259

**Comment by eric-wieser** [comment]
I think this is now fixed.
